### ISSUE TITLE
ZooomableSunburst 

### ISSUE THREAD

**Issue by macgio1** [Trinadhbabu/ZooomableSunburst#1]
I have two issues after i load a dataset, the chart just render the root circle. After i load a second dataset it render the whole sunburst. But the last values get renderd twice. Do you have an idea?
![sunburst_zooming_d3_fehler](https://cloud.githubusercontent.com/assets/25923915/23158542/e4b593b8-f81f-11e6-9dc0-c6ab5015c5d6.png)

**Comment by Trinadhbabu** [comment]
I think I need some more details about the issue.

**Comment by macgio1** [comment]
I documented more detailed with picture. Maybe its better to understand what i mean:

This stage i just load the dataset from an imported json-file:
![pictures2017-02-21_10-55](https://cloud.githubusercontent.com/assets/25923915/23160004/374ffaaa-f825-11e6-86f9-b0dbd0fcd88f.jpg)

After i add a second dataset it renders the rest of the chart:
![2017-02-21_10-59](https://cloud.githubusercontent.com/assets/25923915/23160101/79c75e3c-f825-11e6-9b59-a874518f0cdd.jpg)

I don't add any data of the second dataset. Here the Json-File i imported
[__flare.zip](https://github.com/Trinadhbabu/ZooomableSunburst/files/789747/__flare.zip)

The light blue part (grey) has the same value as the part rendered before:
![2017-02-21_10-59](https://cloud.githubusercontent.com/assets/25923915/23160491/ffd0a38e-f826-11e6-8c62-1e33bc84c9ab.jpg)

It seems that it renders the data two times. I tried with different datasets it turns the same issue. Did you have a similar problem?

Iam developing with the VisBuilder v1.3.0 on MSTR 10.3

**Comment by macgio1** [comment]
I comment this part of the code:

/*var gridData = this.dataInterface;
var rowHeaders = gridData.getRowHeaders();
var attributeName = rowHeaders.titles[0].n;
  for (var i = 0; i < json.length; i++) {
    for (var key in json[i]) {
      if (key !== attributeName) {
        json[i][key] = json[i][key]["rv"] + "";
      }
    }
  }*/

And the problems were solved but i cannot explain why this part creates the problem. I used similar code in other charts it works fine
